### ISSUE TITLE
Navigation spacing pushes the playable area outside of the screen

### ISSUE THREAD

**Issue by haydnjm** [nearform/react-native-workshop#32]
When following [the navigation step](https://github.com/nearform/react-native-workshop/blob/a0b7b46c2b6d005e142d6e4a2d2b87ed19ba0b73/step6-bonus/README.md) in step 6 the spacing that the navigation bar adds means that the playable space goes beyond the bottom of the screen. The size of the navigation needs to be taken into account when calculating the playable area.

**Comment by AlanSl** [comment]
Good catch, thanks for the report! I've updated and force-pushed that branch with some extra content showing how to use React Navigation's `useHeaderHeight` to get the header height and take that into account when feeding the playable height into the game hook
